---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: ns-policy-dev
spec:
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: myapp-dev

